  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  caster_rear_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: caster_rear_joint
   

  gazebo_ros_control/pid_gains:
    caster_rear_joint: {p: 10.0, i: 0.0, d: 0.0}  
